@Library("Shared-lib") _

pipeline {
    agent {label "node1"}
    
    stages {
        stage ("Shared-lib") {
            steps {
                script {
                    hello() 
                    //Test if shared lib works
                }
            }
        }
        
        stage("fetch") {
            steps {
                script {
                    gitclone("https://github.com/Ksab070/django-3tier-notes-app", "main")
                    // Call gitclone function from the shared lib
                }
            }
        }
        
        stage("deploy") {
            steps {
                echo "Deploy phase"
                sh 'docker compose up -d --build' 
                //Build all the containers
            }
        }
    }
}